package main

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"

	btrfsdiff "github.com/mbideau/btrfs-diff-go/pkg"
)

func usage(progname string) {
	fmt.Printf(`
%[1]s - Analyse the differences between two related btrfs subvolumes.

USAGE

	%[1]s [ --debug ] PARENT CHILD
		Analyse the difference between btrfs PARENT and CHILD.

	%[1]s [ --debug ] -f|--file STREAM
		Analyse the differences from a STREAM file (output from 'btrfs send').

	%[1]s [ -h | --help ]
		Display help.

ARGUMENTS

	PARENT
		A btrfs subvolume that is the parent of the CHILD one.

	CHILD
		A btrfs subvolume that is the child of the PARENT one.

OPTIONS

	-h | --help
		Display help.

	--debug
		Be more verbose.

	-f|--file STREAM
		Use a STREAM file to get the btrfs operations.
		This stream file must have been generated by the command
		'btrfs send' (with or without the option --no-data).

EXAMPLES

	Get the differences between two snapshots.
	$ %[1]s /backup/btrfs-sp/rootfs/2020-12-25_22h00m00.shutdown.safe \
		/backup/btrfs-sp/rootfs/2019-12-25_21h00m00.shutdown.safe

AUTHORS

	Originally written by: David Buckley
	Extended, fixed, and maintained by: Michael Bideau

REPORTING BUGS
	Report bugs to: <https://github.com/mbideau/btrfs-diff-go/issues>

COPYRIGHT

	Copyright © 2020-2021 Michael Bideau.
	License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.

	Info: original license chosen by David Buckley was MIT, but it allows sublicensing, so I
	      chose to sublicense it to GPLv3+ to ensure code sharing

SEE ALSO

	Home page: <https://github.com/mbideau/btrfs-diff-go>

`, progname)
}

func main() {
	var first string
	var second string
	if len(os.Args) <= 2 || os.Args[1] == "-h" || os.Args[1] == "--help" {
		usage(path.Base(os.Args[0]))
	} else {
		first = os.Args[1]
		second = os.Args[2]
		if len(os.Args) == 4 && first == "--debug" {
			fmt.Println("[DEBUG] Debug enabled")
			btrfsdiff.SetDebug(true)
			first = os.Args[2]
			second = os.Args[3]
		}

		var changes []string
		var err error

		// --file option specified with a stream file
		if first == "-f" || first == "--file" {
			var streamfile string
			streamfile, _ = filepath.Abs(second)
			changes, err = btrfsdiff.GetChangesFromStreamFile(streamfile)

			// parent and child arguments
		} else {

			var parent string
			var child string
			parent, _ = filepath.Abs(first)
			child, _ = filepath.Abs(second)
			changes, err = btrfsdiff.GetChangesFromTwoSubvolumes(child, parent)
		}

		if err != nil {
			fmt.Fprintf(os.Stderr, "%v\n", err)
			os.Exit(1)
		}

		// if there are changes/differences
		if len(changes) > 0 {

			// print changes
			fmt.Printf("%v\n", strings.Join(changes, "\n"))

			// exit 1 if there are differences
			os.Exit(1)
		}
	}
}
