# This is a basic workflow to help you get started with Actions

name: golang

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-16.04

    strategy:
      matrix:
        go: [ '1.14', '1.15', '1.16' ]

    name: Go ${{ matrix.go }} build

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install required packages dependencies
      - name: Install required packages dependencies
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get -q -y install libbtrfs-dev

      # Setup different version of golang
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      # Build the binary
      - name: Building the binary
        run: go build -v
