# This is a basic workflow to help you get started with Actions

name: Go static analysis

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-16.04

    strategy:
      matrix:
        go: [ '1.14', '1.15', '1.16' ]

    name: Go ${{ matrix.go }} analysis

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install required packages dependencies
      - name: Install required packages dependencies
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get -q -y install libbtrfs-dev

      # Setup different version of golang
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      # Install required packages dependencies
      - name: Install required packages dependencies
        run: |
          go get -u \
            github.com/kisielk/errcheck \
            golang.org/x/tools/cmd/goimports \
            golang.org/x/lint/golint \
            github.com/securego/gosec/cmd/gosec \
            golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow \
            honnef.co/go/tools/cmd/staticcheck

      # Static analysis checks
      - name: Linting (golint)
        run: golint -set_exit_status ./...

      - name: Formatting (gofmt)
        run: gofmt -l -s .

      - name: Error checking (errcheck)
        run: errcheck ./...

      - name: Imports checks (goimports)
        run: goimports -l .

      - name: Linting (govet)
        run: go vet ./...

      - name: Linting (shadow)
        run: go vet -vettool=/go/bin/shadow ./...

      - name: Security checks (gosec)
        run: gosec -out result.txt ./...

      - name: Static analysis (staticcheck)
        run: staticcheck ./...
